{literal}
{extends file="Master.tpl"}

{block name=title}{/literal}{$appname}{literal} | Home{/block}

{block name=container}

	<div class="container">

		<!-- Main hero unit for a primary marketing message or call to action -->
		<div class="hero-unit">
			<h1>Congratulations!</h1>
			<p>This application has been automatically generated by Phreeze.  This code should be
			considered a starting point with much of the repetitive work done, leaving you to
			focus on your application-specific functionality.  Read below for more information about
			the technologies used to build this application.</p>
			<p><a class="btn btn-primary btn-large" href="http://phreeze.com/">Get Started &raquo;</a></p>
		</div>

		<!-- Example row of columns -->
		<div class="row">
			<div class="span4">
				<h2>Phreeze</h2>
				 <p>Phreeze is a MVC+ORM framework for PHP that provides
				 URL Routing, a Model layer with object-oriented database access and
				 RESTful JSON services which are consumed by the view layer.</p>
				<p><a class="btn" href="http://phreeze.com/">About Phreeze &raquo;</a></p>
			</div>
			<div class="span4">
				<h2>Backbone</h2>
				 <p>Backbone.js is a Javascript framework that serves as an MVC for the view layer, providing models,
				 binding and custom events, collections with a rich API of enumerable functions, views
				 with declarative event handling.</p>
				<p><a class="btn" href="http://documentcloud.github.com/backbone/">About Backbone &raquo;</a></p>
		 </div>
			<div class="span4">
				<h2>Bootstrap</h2>
				<p>This application uses Bootstrap by Twitter to provide clean, cross-browser layout and UI.
				Bootstrap provides Simple and flexible HTML, CSS, and Javascript for popular user interface
				components and interactions.</p>
				<p><a class="btn" href="http://twitter.github.com/bootstrap/">About Bootstrap &raquo;</a></p>
			</div>
		</div>

		<hr>

		<footer>
			<p>&copy; {/literal}{$appname}{literal} {$smarty.now|date_format:'%Y'}</p>
		</footer>

	</div> <!-- /container -->

{/block}
{/literal}